name: Deploy documentation on Github Pages

on:
  push:
    branches: [ "main" ]

jobs:  
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Pre-bootstrap
        run: make pre-bootstrap

      - name: Build docs
        run: make docs-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-openapi
          path: .docs/openapi.json
    
  deploy-docs:
    permissions:
      contents: write
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-openapi
          path: artifacts

      - name: Copy artifacts
        run: mkdir .docs/ && cp artifacts/openapi.json .docs/openapi.json

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install docs dependencies
        run: pip install ./docs

      - name: Check location
        run : ls -al

      - name: Deploying to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "APUI BOT"
          git config --global user.email "apuibot@users.noreply.github.com"
          git fetch origin gh-pages
          # Deploy docs with either:
          # - DOCS_VERSION: 1.1 (for git tag v1.1.2)
          # - DOCS_ALIAS: latest
          # or
          # - DOCS_VERSION: dev (for main branch)
          # - No DOCS_ALIAS
          DOCS_VERSION=$([[ "$GITHUB_REF_TYPE" == "tag" ]] && echo "$GITHUB_REF_NAME" | sed 's/^v\([0-9]\.[0-9]*\)\..*/\1/' || echo "dev")
          DOCS_ALIAS=$([[ "$GITHUB_REF_TYPE" == "tag" ]] && echo "latest" || echo "")
          echo "DOCS_VERSION: ${DOCS_VERSION}"
          echo "DOCS_ALIAS: ${DOCS_ALIAS}"
          # Build docs
          mike deploy $DOCS_VERSION $DOCS_ALIAS
          # Set default doc to point to
          mike set-default dev
          # Push build docs
          mike deploy --push --update-aliases $DOCS_VERSION $DOCS_ALIAS
