name: Frontend service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pre-Bootstrap
        run: make pre-bootstrap

      - name: Build Docker front-end
        run: make build-docker-frontend

      # To preserve permissions, we need to tar the node_modules folder
      # https://github.com/actions/upload-artifact#permission-loss
      - name: Make node_modules tar archives
        run: |
          mkdir artifacts
          tar cf artifacts/node_modules.tar src/frontend/apps/web/node_modules \
            src/frontend/node_modules \
            src/frontend/packages/tdbp/node_modules \
            src/frontend/packages/eslint-config-custom/node_modules
          
      - name: Export Docker image
        run: |
          docker save warren-tdbp:frontend-development > artifacts/warren-frontend.tar

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: artifacts
          retention-days: 1
          compression-level: 0

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v4
        with:
          name: build
          path: artifacts

      - name: Load Docker image
        run: docker load -i artifacts/warren-frontend.tar

      - name: Pre-Bootstrap
        run: make pre-bootstrap

      - name: Extract node_modules artifacts
        run: |
          tar xf artifacts/node_modules.tar
          
      - name: Lint code
        run: |
          make lint-frontend
