name: Documentation service CI

on:
  pull_request:
    branches: [ "main" ]

jobs:  
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Pre-bootstrap
        run: make pre-bootstrap

      - name: Build docs
        run: make docs-build
